import { db } from '@/lib/db'

// Every auto-task has a unique key per project.
// The engine checks this before creating, so duplicates are impossible.
export const AUTO_KEYS = {
  NEED_ENGINEERING:   'need_engineering',
  NEED_MATERIALS:     'need_materials_list',
  NEED_CLIENT_INFO:   'need_client_info',
  ORDER_MATERIALS:    'order_materials',
  START_PROJECT_NOTICE:'start_project_notice',
  CONFIRM_VENDOR:     'confirm_vendor',
  VERIFY_RECEIVED:    'verify_materials_received',
  FOLLOWUP_MATERIALS: 'followup_materials',
  CREW_CONFIRM:       'crew_confirm_materials',
  RESOLVE_MINOR:      'resolve_minor_items',
  JOBSITE_CHECK:      'jobsite_check',
  RESOLVE_CHANGES:    'resolve_vs_engineering',
} as const

function subtractDays(dateStr: string, days: number): string {
  const d = new Date(dateStr)
  d.setDate(d.getDate() - days)
  return d.toISOString().split('T')[0]
}

function todayStr(): string {
  return new Date().toISOString().split('T')[0]
}

function startReminderTitle(projectName: string, scheduleDate: string): string {
  return `4-day start reminder: project ${projectName} starts on ${scheduleDate}`
}

export async function runProjectAutomation(projectId: string): Promise<void> {
  const project = await db.projects.findUnique({
    where: { id: projectId },
    include: {
      materials: true,
      documents: true,
      client: true,
      tasks: {
        where: { autoGenerated: true, status: 'pending' },
        select: { automationKey: true },
      },
    },
  })

  if (!project) return

  // Keys that already have a live auto-task → skip creation
  const existing = new Set(
    project.tasks.map((t) => t.automationKey).filter((k): k is string => k !== null && k !== undefined)
  )

  async function ensure(key: string, title: string, dueDate?: string, priority = 2) {
    if (existing.has(key)) return
    await db.tasks.create({
      data: {
        projectId,
        title,
        dueDate: dueDate ?? null,
        automationKey: key,
        autoGenerated: true,
        priority,
        status: 'pending',
      },
    })
  }

  async function resolve(key: string) {
    await db.tasks.updateMany({
      where: { projectId, automationKey: key, status: 'pending', autoGenerated: true },
      data: { status: 'completed', completedAt: todayStr() },
    })
  }

  const { status, startDate, materials, documents, client } = project

  // ── Computed conditions ───────────────────────────────────────────────────
  const hasEngineering  = documents.some((d) => d.category === 'engineering')
  const hasMaterialsList = materials.length > 0
  const clientOk        = !!(client?.name?.trim() && client?.phone?.trim())

  const totalPlanned    = materials.reduce((s, m) => s + m.plannedQuantity, 0)
  const totalDispatched = materials.reduce((s, m) => s + m.dispatchedQuantity, 0)
  const materialPct     = totalPlanned > 0 ? totalDispatched / totalPlanned : 0

  // ── 1. PLANNED / SCHEDULED — prerequisite reminders ──────────────────────
  if (status === 'planned' || status === 'scheduled') {
    if (!hasEngineering)   await ensure(AUTO_KEYS.NEED_ENGINEERING, 'Upload engineering document', undefined, 1)
    else                   await resolve(AUTO_KEYS.NEED_ENGINEERING)

    if (!hasMaterialsList) await ensure(AUTO_KEYS.NEED_MATERIALS, 'Create materials list', undefined, 1)
    else                   await resolve(AUTO_KEYS.NEED_MATERIALS)

    if (!clientOk)         await ensure(AUTO_KEYS.NEED_CLIENT_INFO, 'Complete client information', undefined, 2)
    else                   await resolve(AUTO_KEYS.NEED_CLIENT_INFO)
  }

  // ── 2. SCHEDULED — timeline tasks based on startDate ─────────────────────
  const scheduleDate = startDate
  if (status === 'scheduled' && scheduleDate && hasMaterialsList) {
    await ensure(AUTO_KEYS.START_PROJECT_NOTICE, startReminderTitle(project.name, scheduleDate), subtractDays(scheduleDate, 4), 1)
    await ensure(AUTO_KEYS.ORDER_MATERIALS, 'Order materials',           subtractDays(scheduleDate, 4), 1)
    await ensure(AUTO_KEYS.CONFIRM_VENDOR,  'Confirm order with vendor', subtractDays(scheduleDate, 3), 1)
    await ensure(AUTO_KEYS.VERIFY_RECEIVED, 'Verify materials received', subtractDays(scheduleDate, 1), 1)
  } else {
    await resolve(AUTO_KEYS.START_PROJECT_NOTICE)
    await resolve(AUTO_KEYS.ORDER_MATERIALS)
    await resolve(AUTO_KEYS.CONFIRM_VENDOR)
    await resolve(AUTO_KEYS.VERIFY_RECEIVED)
  }

  // ── 3. MATERIAL FOLLOW-UP ─────────────────────────────────────────────────
  const trackStatuses = ['scheduled', 'dispatched', 'in_progress']
  if (trackStatuses.includes(status) && hasMaterialsList) {
    if (materialPct < 1) await ensure(AUTO_KEYS.FOLLOWUP_MATERIALS, 'Follow up on missing materials', undefined, 1)
    else                 await resolve(AUTO_KEYS.FOLLOWUP_MATERIALS)
  }

  // ── 4. DISPATCHED ─────────────────────────────────────────────────────────
  if (status === 'dispatched') {
    await ensure(AUTO_KEYS.CREW_CONFIRM,  'Confirm crew has all materials', startDate ?? undefined, 1)
    await ensure(AUTO_KEYS.RESOLVE_MINOR, 'Resolve minor missing items',    undefined, 2)
  }

  // ── 5. IN PROGRESS ────────────────────────────────────────────────────────
  if (status === 'in_progress') {
    await ensure(AUTO_KEYS.JOBSITE_CHECK,   'Check jobsite issues',               undefined, 2)
    await ensure(AUTO_KEYS.RESOLVE_CHANGES, 'Resolve changes vs engineering plan', undefined, 2)
  }
}

export async function autoScheduleProject(projectId: string): Promise<boolean> {
  const project = await db.projects.findUnique({
    where: { id: projectId },
    select: {
      status: true,
      startDate: true,
      _count: { select: { materials: true } },
    },
  })

  if (!project) return false
  if (project.status !== 'planned') return false
  if (!project.startDate || project._count.materials === 0) return false

  await db.projects.update({
    where: { id: projectId },
    data: { status: 'scheduled' },
  })
  await runProjectAutomation(projectId)
  return true
}

export async function autoPlanProjectIfNoMaterials(projectId: string): Promise<boolean> {
  const project = await db.projects.findUnique({
    where: { id: projectId },
    select: {
      status: true,
      _count: { select: { materials: true } },
    },
  })

  if (!project) return false
  if (project.status !== 'scheduled') return false
  if (project._count.materials > 0) return false

  await db.projects.update({
    where: { id: projectId },
    data: { status: 'planned' },
  })
  await runProjectAutomation(projectId)
  return true
}

// Returns the single highest-priority pending task for a project.
// Used as the project's "Next Action" without any extra query.
export async function getNextAction(projectId: string) {
  const today = todayStr()
  return db.tasks.findFirst({
    where: {
      projectId,
      status: 'pending',
      OR: [
        { dueDate: null },
        { dueDate: { lte: today } },
      ],
    },
    orderBy: [{ priority: 'asc' }, { dueDate: 'asc' }, { createdAt: 'asc' }],
    select: {
      id: true,
      title: true,
      dueDate: true,
      priority: true,
      autoGenerated: true,
      automationKey: true,
    },
  })
}
