export type TaskBucket = 'overdue' | 'today' | 'this_week' | 'later' | 'completed'

export interface BucketableTask {
  status: string
  dueDate: string | null
  alarmDate: string | null
  completedAt: string | null
  autoGenerated?: boolean
  automationKey?: string | null
  project?: {
    name: string
    poNumber?: string | null
    startDate?: string | null
    status?: string | null
    materialsPlannedTotal?: number
    materialsDispatchedTotal?: number
  } | null
}

function todayLocal(): Date {
  const n = new Date()
  return new Date(n.getFullYear(), n.getMonth(), n.getDate())
}

function parseLocal(dateStr: string): Date | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(dateStr)
  if (!m) return null
  return new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]))
}

export function daysBetween(a: Date, b: Date): number {
  const ms = 24 * 60 * 60 * 1000
  return Math.round((a.getTime() - b.getTime()) / ms)
}

export function getEffectiveDueDate(task: BucketableTask): string | null {
  return task.dueDate || task.alarmDate || null
}

export function bucketTask(task: BucketableTask, today: Date = todayLocal()): TaskBucket {
  if (task.status === 'completed') return 'completed'
  const dueStr = getEffectiveDueDate(task)
  if (!dueStr) return 'later'
  const due = parseLocal(dueStr)
  if (!due) return 'later'
  const days = daysBetween(due, today)
  if (days < 0) return 'overdue'
  if (days <= 1) return 'today'
  if (days <= 7) return 'this_week'
  return 'later'
}

export interface BucketStyle {
  border: string
  background: string
  pillBg: string
  pillText: string
  pillBorder: string
  sectionTint: string
  sectionLabel: string
  icon: string
}

export function getBucketStyle(bucket: TaskBucket): BucketStyle {
  switch (bucket) {
    case 'overdue':
      return {
        border: 'border-l-rose-500',
        background: 'bg-rose-50/60 hover:bg-rose-50',
        pillBg: 'bg-rose-500',
        pillText: 'text-white',
        pillBorder: 'border-rose-500',
        sectionTint: 'bg-gradient-to-r from-rose-50 to-transparent',
        sectionLabel: 'text-rose-700',
        icon: 'rose',
      }
    case 'today':
      return {
        border: 'border-l-amber-500',
        background: 'bg-amber-50/60 hover:bg-amber-50',
        pillBg: 'bg-amber-500',
        pillText: 'text-white',
        pillBorder: 'border-amber-500',
        sectionTint: 'bg-gradient-to-r from-amber-50 to-transparent',
        sectionLabel: 'text-amber-700',
        icon: 'amber',
      }
    case 'this_week':
      return {
        border: 'border-l-sky-400',
        background: 'hover:bg-sky-50/60',
        pillBg: 'bg-sky-100',
        pillText: 'text-sky-700',
        pillBorder: 'border-sky-200',
        sectionTint: 'bg-gradient-to-r from-sky-50 to-transparent',
        sectionLabel: 'text-sky-700',
        icon: 'sky',
      }
    case 'completed':
      return {
        border: 'border-l-emerald-300',
        background: 'hover:bg-emerald-50/40',
        pillBg: 'bg-emerald-50',
        pillText: 'text-emerald-700',
        pillBorder: 'border-emerald-200',
        sectionTint: 'bg-gradient-to-r from-emerald-50 to-transparent',
        sectionLabel: 'text-emerald-700',
        icon: 'emerald',
      }
    case 'later':
    default:
      return {
        border: 'border-l-slate-300',
        background: 'hover:bg-slate-50',
        pillBg: 'bg-slate-100',
        pillText: 'text-slate-600',
        pillBorder: 'border-slate-200',
        sectionTint: '',
        sectionLabel: 'text-slate-600',
        icon: 'slate',
      }
  }
}

export function formatRelativeDue(dateStr: string, today: Date = todayLocal()): string {
  const due = parseLocal(dateStr)
  if (!due) return ''
  const days = daysBetween(due, today)
  if (days < 0) return `Vencido ${days}d`
  if (days === 0) return 'Hoy'
  if (days === 1) return 'Mañana'
  if (days <= 7) return `En ${days} días`
  // Show short date for far-future
  return new Intl.DateTimeFormat('es', { day: 'numeric', month: 'short' }).format(due)
}

export function formatStartsIn(daysToStart: number): string {
  if (daysToStart < 0) return `Inició hace ${Math.abs(daysToStart)} días`
  if (daysToStart === 0) return 'Inicia hoy'
  if (daysToStart === 1) return 'Inicia mañana'
  return `Inicia en ${daysToStart} días`
}

export interface EnrichedContext {
  contextLine: string
  dispatchedPct?: number
}

export function enrichAutoTask(task: BucketableTask, today: Date = todayLocal()): EnrichedContext | null {
  if (!task.autoGenerated || !task.project) return null
  const project = task.project
  const startDate = project.startDate ? parseLocal(project.startDate) : null
  const daysToStart = startDate ? daysBetween(startDate, today) : null
  const planned = project.materialsPlannedTotal ?? 0
  const dispatched = project.materialsDispatchedTotal ?? 0
  const pct = planned > 0 ? Math.round((dispatched / planned) * 100) : 0
  const startsInLine = daysToStart !== null ? formatStartsIn(daysToStart) : null

  const parts: (string | null)[] = []

  switch (task.automationKey) {
    case 'need_engineering':
      parts.push('Sin documento de ingeniería')
      break
    case 'need_materials_list':
      parts.push('Sin lista de materiales')
      break
    case 'need_client_info':
      parts.push('Falta información del cliente')
      break
    case 'order_materials':
      parts.push(startsInLine, planned > 0 ? `${pct}% despachado` : null)
      break
    case 'start_project_notice':
      parts.push(
        startsInLine,
        project.status ? `Status: ${project.status}` : null,
      )
      break
    case 'confirm_vendor':
      parts.push(startsInLine, 'Pedido pendiente de confirmación')
      break
    case 'verify_materials_received':
      parts.push(startsInLine, planned > 0 ? `${pct}% recibido` : null)
      break
    case 'followup_materials':
      parts.push(planned > 0 ? `${100 - pct}% pendiente de despacho` : 'Materiales pendientes')
      break
    case 'crew_confirm_materials':
      parts.push(startsInLine, planned > 0 ? `${pct}% despachado` : null)
      break
    case 'resolve_minor_items':
      parts.push('Items menores pendientes')
      break
    case 'jobsite_check':
      parts.push('Revisar incidencias del proyecto')
      break
    case 'resolve_vs_engineering':
      parts.push('Resolver cambios vs plano')
      break
    default:
      return null
  }

  const contextLine = parts.filter(Boolean).join(' · ')
  if (!contextLine) return null
  return { contextLine, dispatchedPct: planned > 0 ? pct : undefined }
}

export function bucketLabel(bucket: TaskBucket): string {
  switch (bucket) {
    case 'overdue': return 'Vencidas'
    case 'today': return 'Hoy y mañana'
    case 'this_week': return 'Esta semana'
    case 'later': return 'Más adelante'
    case 'completed': return 'Completadas'
  }
}

export function bucketEmoji(bucket: TaskBucket): string {
  switch (bucket) {
    case 'overdue': return '🔴'
    case 'today': return '🟡'
    case 'this_week': return '📅'
    case 'later': return '🗓️'
    case 'completed': return '✅'
  }
}

export function isDateWithinNDays(dateStr: string | null, n: number, today: Date = todayLocal()): boolean {
  if (!dateStr) return false
  const d = parseLocal(dateStr)
  if (!d) return false
  const days = daysBetween(today, d)
  return days >= 0 && days <= n
}
