'use client'

import { Bell, Building2, Check, ExternalLink, HardHat, Pencil, Trash2, Moon, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  bucketTask,
  enrichAutoTask,
  formatRelativeDue,
  getBucketStyle,
  getEffectiveDueDate,
  type BucketableTask,
} from '@/lib/task-bucketing'

interface TaskProject {
  id: string
  name: string
  poNumber?: string | null
  startDate?: string | null
  status?: string | null
  materialsPlannedTotal?: number
  materialsDispatchedTotal?: number
}

export interface TaskLike extends BucketableTask {
  id: string
  title: string
  description: string
  dueDate: string | null
  alarmDate: string | null
  completedAt: string | null
  projectId: string | null
  status: string
  createdAt: string
  autoGenerated?: boolean
  automationKey?: string | null
  priority?: number
  assigneeType?: 'contractor' | 'installer' | null
  assigneeId?: string | null
  project?: TaskProject | null
}

interface Props {
  task: TaskLike
  expanded?: boolean
  toggling?: boolean
  hideProjectContext?: boolean
  assigneeName?: string
  onClickRow?: () => void
  onToggleComplete: () => void
  onSnooze?: () => void
  onEdit: () => void
  onDelete: () => void
  onOpenProject?: () => void
}

function shortDate(dateStr: string): string {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(dateStr)
  if (!m) return dateStr
  const d = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]))
  return new Intl.DateTimeFormat('es', { day: 'numeric', month: 'short', year: 'numeric' }).format(d)
}

export function TaskRow({
  task,
  expanded = false,
  toggling = false,
  hideProjectContext = false,
  assigneeName,
  onClickRow,
  onToggleComplete,
  onSnooze,
  onEdit,
  onDelete,
  onOpenProject,
}: Props) {
  const bucket = bucketTask(task)
  const style = getBucketStyle(bucket)
  const enrichment = enrichAutoTask(task)
  const dueStr = getEffectiveDueDate(task)
  const isUrgent = task.priority === 1
  const isCompleted = task.status === 'completed'
  const AssigneeIcon = task.assigneeType === 'installer' ? HardHat : Building2

  const projectLabel = task.project
    ? task.project.poNumber
      ? `${task.project.name} · PO ${task.project.poNumber}`
      : task.project.name
    : null

  return (
    <div
      className={`group relative grid grid-cols-[24px_1fr_auto] items-start gap-2.5 rounded-md border-l-2 px-3 py-2 transition-colors cursor-pointer ${style.border} ${style.background} ${expanded ? 'border border-slate-300 bg-white shadow-sm' : ''}`}
      onClick={(e) => {
        if ((e.target as HTMLElement).closest('[data-no-row-click]')) return
        onClickRow?.()
      }}
    >
      {/* Checkbox */}
      <div data-no-row-click>
        <button
          type="button"
          onClick={(e) => {
            e.stopPropagation()
            onToggleComplete()
          }}
          disabled={toggling}
          className={`mt-0.5 flex h-5 w-5 items-center justify-center rounded border transition-colors ${
            isCompleted
              ? 'border-emerald-500 bg-emerald-500 text-white'
              : 'border-slate-300 bg-white hover:border-emerald-500'
          }`}
          aria-label={isCompleted ? 'Marcar como pendiente' : 'Marcar como hecho'}
        >
          {toggling ? <Loader2 className="h-3 w-3 animate-spin" /> : isCompleted && <Check className="h-3 w-3" strokeWidth={3} />}
        </button>
      </div>

      {/* Body */}
      <div className="min-w-0">
        <div className="flex flex-wrap items-center gap-1.5">
          {isUrgent && !isCompleted && (
            <span
              className="h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500 ring-2 ring-rose-100"
              title="Alta prioridad"
            />
          )}
          <span
            className={`text-[13.5px] font-semibold leading-snug ${
              isCompleted ? 'text-slate-400 line-through' : 'text-slate-800'
            }`}
          >
            {task.title}
          </span>
          {task.autoGenerated ? (
            <span className="rounded border border-violet-200 bg-violet-50 px-1.5 py-0.5 text-[9.5px] font-bold uppercase tracking-wide text-violet-700">
              Auto
            </span>
          ) : (
            <span className="rounded border border-slate-200 bg-slate-50 px-1.5 py-0.5 text-[9.5px] font-bold uppercase tracking-wide text-slate-500">
              Manual
            </span>
          )}
          {assigneeName && (
            <span className="inline-flex items-center gap-1 rounded border border-cyan-100 bg-cyan-50 px-1.5 py-0.5 text-[10.5px] font-medium text-cyan-700">
              <AssigneeIcon className="h-2.5 w-2.5" />
              {assigneeName}
            </span>
          )}
        </div>

        {/* Context line */}
        {!isCompleted && (enrichment || (projectLabel && !hideProjectContext)) && (
          <div className="mt-1 flex flex-wrap items-center gap-x-1.5 gap-y-0.5 text-[11.5px] text-slate-500">
            {!hideProjectContext && projectLabel && (
              <span className="font-medium text-slate-700">{projectLabel}</span>
            )}
            {!hideProjectContext && projectLabel && enrichment && (
              <span className="text-slate-300">·</span>
            )}
            {enrichment && <span>{enrichment.contextLine}</span>}
          </div>
        )}

        {/* Expanded details */}
        {expanded && (
          <div className="mt-2.5 space-y-2 border-t border-dashed border-slate-200 pt-2.5 text-[12px]" data-no-row-click>
            {task.description && (
              <div>
                <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Descripción</div>
                <div className="text-slate-600">{task.description}</div>
              </div>
            )}
            <div className="flex flex-wrap gap-x-5 gap-y-1.5">
              {task.dueDate && (
                <div>
                  <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Fecha límite</div>
                  <div className="text-slate-700">{shortDate(task.dueDate)}</div>
                </div>
              )}
              {task.alarmDate && (
                <div>
                  <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Alarma</div>
                  <div className="flex items-center gap-1 text-amber-700">
                    <Bell className="h-3 w-3" /> {shortDate(task.alarmDate)}
                  </div>
                </div>
              )}
              <div>
                <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Creada</div>
                <div className="text-slate-700">{shortDate(task.createdAt)}</div>
              </div>
              {task.completedAt && (
                <div>
                  <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Completada</div>
                  <div className="text-emerald-700">{shortDate(task.completedAt)}</div>
                </div>
              )}
            </div>
            {task.project && onOpenProject && (
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation()
                  onOpenProject()
                }}
                className="inline-flex items-center gap-1 text-sky-600 hover:text-sky-700 hover:underline"
              >
                <ExternalLink className="h-3 w-3" /> Ir a {task.project.name}
              </button>
            )}
            <div className="flex flex-wrap gap-1.5 pt-1">
              {onSnooze && !isCompleted && (
                <Button
                  size="sm"
                  variant="outline"
                  className="h-7 gap-1 border-amber-200 bg-amber-50 px-2 text-[11.5px] text-amber-700 hover:bg-amber-100"
                  onClick={(e) => {
                    e.stopPropagation()
                    onSnooze()
                  }}
                >
                  <Moon className="h-3 w-3" /> Snooze 1 día
                </Button>
              )}
              <Button
                size="sm"
                variant="outline"
                className="h-7 gap-1 px-2 text-[11.5px]"
                onClick={(e) => {
                  e.stopPropagation()
                  onEdit()
                }}
              >
                <Pencil className="h-3 w-3" /> Editar
              </Button>
              <Button
                size="sm"
                variant="outline"
                className="ml-auto h-7 gap-1 border-rose-200 bg-white px-2 text-[11.5px] text-rose-600 hover:bg-rose-50"
                onClick={(e) => {
                  e.stopPropagation()
                  onDelete()
                }}
              >
                <Trash2 className="h-3 w-3" /> Eliminar
              </Button>
            </div>
          </div>
        )}
      </div>

      {/* Meta */}
      <div className="flex items-start gap-1" data-no-row-click>
        {dueStr && (
          <span
            className={`inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold tabular-nums ${
              bucket === 'completed' && task.completedAt
                ? 'border border-emerald-200 bg-emerald-50 text-emerald-700'
                : `${style.pillBg} ${style.pillText} ${bucket === 'this_week' || bucket === 'later' ? `border ${style.pillBorder}` : ''}`
            }`}
          >
            {formatRelativeDue(dueStr)}
          </span>
        )}
        {!expanded && (
          <div className="flex items-center opacity-0 transition-opacity group-hover:opacity-100">
            {onSnooze && !isCompleted && (
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation()
                  onSnooze()
                }}
                className="flex h-6 w-6 items-center justify-center rounded text-slate-400 hover:bg-slate-200 hover:text-slate-700"
                title="Snooze 1 día"
              >
                <Moon className="h-3.5 w-3.5" />
              </button>
            )}
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation()
                onEdit()
              }}
              className="flex h-6 w-6 items-center justify-center rounded text-slate-400 hover:bg-slate-200 hover:text-slate-700"
              title="Editar"
            >
              <Pencil className="h-3.5 w-3.5" />
            </button>
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation()
                onDelete()
              }}
              className="flex h-6 w-6 items-center justify-center rounded text-slate-400 hover:bg-rose-100 hover:text-rose-600"
              title="Eliminar"
            >
              <Trash2 className="h-3.5 w-3.5" />
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
