'use client'

import { useMemo } from 'react'
import { bucketTask, isDateWithinNDays, type BucketableTask } from '@/lib/task-bucketing'

export type KpiKey = 'overdue' | 'today' | 'this_week' | 'done7d' | 'auto_pending'

interface Props {
  tasks: BucketableTask[]
  activeKey: KpiKey | null
  onSelect: (key: KpiKey | null) => void
}

interface KpiConfig {
  key: KpiKey
  emoji: string
  label: string
  borderClass: string
  numClass: string
  bgClass: string
}

const KPI_CONFIG: KpiConfig[] = [
  { key: 'overdue', emoji: '🔴', label: 'Vencidas', borderClass: 'border-l-rose-500', numClass: 'text-rose-600', bgClass: 'bg-white' },
  { key: 'today', emoji: '🟡', label: 'Hoy y mañana', borderClass: 'border-l-amber-500', numClass: 'text-amber-700', bgClass: 'bg-white' },
  { key: 'this_week', emoji: '📅', label: 'Esta semana', borderClass: 'border-l-sky-400', numClass: 'text-sky-700', bgClass: 'bg-white' },
  { key: 'done7d', emoji: '✅', label: 'Hechas (7d)', borderClass: 'border-l-emerald-500', numClass: 'text-emerald-700', bgClass: 'bg-white' },
  { key: 'auto_pending', emoji: '🤖', label: 'Auto pendientes', borderClass: 'border-l-violet-600', numClass: 'text-violet-700', bgClass: 'bg-violet-50/40' },
]

export function TaskKpiStrip({ tasks, activeKey, onSelect }: Props) {
  const counts = useMemo(() => {
    const c: Record<KpiKey, number> = {
      overdue: 0,
      today: 0,
      this_week: 0,
      done7d: 0,
      auto_pending: 0,
    }
    for (const t of tasks) {
      const b = bucketTask(t)
      if (b === 'overdue') c.overdue++
      else if (b === 'today') c.today++
      else if (b === 'this_week') c.this_week++
      else if (b === 'completed') {
        if (isDateWithinNDays(t.completedAt, 7)) c.done7d++
      }
      if (t.autoGenerated && t.status !== 'completed') c.auto_pending++
    }
    return c
  }, [tasks])

  return (
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">
      {KPI_CONFIG.map((cfg) => {
        const active = activeKey === cfg.key
        const count = counts[cfg.key]
        return (
          <button
            key={cfg.key}
            type="button"
            onClick={() => onSelect(active ? null : cfg.key)}
            className={`group relative rounded-lg border border-slate-200 border-l-[3px] px-3.5 py-3 text-left transition-all ${cfg.borderClass} ${cfg.bgClass} ${
              active
                ? 'ring-2 ring-slate-900 ring-offset-1'
                : 'hover:-translate-y-px hover:shadow-md'
            }`}
            title={`Filtrar por ${cfg.label}`}
          >
            <div className={`text-[22px] font-bold leading-none tabular-nums ${cfg.numClass}`}>{count}</div>
            <div className="mt-1 flex items-center gap-1.5 text-[11.5px] font-medium text-slate-500">
              <span>{cfg.emoji}</span>
              <span>{cfg.label}</span>
            </div>
          </button>
        )
      })}
    </div>
  )
}
