'use client'

import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Bell, Building2, CheckCircle2, Circle, Filter, FolderKanban, HardHat, ListTodo, Pencil, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { useI18n } from '@/components/layout/I18nProvider'
import { ConfirmDeleteDialog } from '@/components/shared/ConfirmDeleteDialog'
import { EmptyState } from '@/components/shared/EmptyState'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Textarea } from '@/components/ui/textarea'
import { formatLocaleDate } from '@/lib/i18n/format'
import type { MessageKey } from '@/lib/i18n/messages'

interface Task {
  id: string
  title: string
  description: string
  dueDate: string | null
  alarmDate: string | null
  completedAt: string | null
  projectId: string | null
  status: string
  createdAt: string
  autoGenerated?: boolean
  automationKey?: string | null
  priority?: number
  assigneeType?: 'contractor' | 'installer' | null
  assigneeId?: string | null
  project?: TaskProject | null
}

interface TaskProject {
  id: string
  name: string
  poNumber?: string | null
}

interface PersonOption {
  type: 'contractor' | 'installer'
  id: string
  name: string
}

interface TaskFormData {
  title: string
  description: string
  dueDate: string
  alarmDate: string
  completedAt: string
  projectId: string
  status: string
  assigneeKey: string
}

const emptyForm: TaskFormData = {
  title: '',
  description: '',
  dueDate: '',
  alarmDate: '',
  completedAt: '',
  projectId: '',
  status: 'pending',
  assigneeKey: '',
}

const NO_PROJECT_VALUE = '__none__'
const NO_ASSIGNEE_VALUE = '__none__'

function makeAssigneeKey(type: 'contractor' | 'installer' | null | undefined, id: string | null | undefined) {
  if (!type || !id) return ''
  return `${type}:${id}`
}

function parseAssigneeKey(key: string) {
  if (!key) return { assigneeType: null as 'contractor' | 'installer' | null, assigneeId: null as string | null }
  const [type, id] = key.split(':')
  if ((type === 'contractor' || type === 'installer') && id) return { assigneeType: type, assigneeId: id }
  return { assigneeType: null, assigneeId: null }
}

function getTaskStatusKey(status: string): MessageKey {
  switch (status) {
    case 'in_progress':
      return 'dashboard.status.inProgress'
    case 'completed':
      return 'dashboard.status.completed'
    case 'pending':
    default:
      return 'dashboard.status.pending'
  }
}

const STATUS_CLASSNAME: Record<string, string> = {
  pending: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300',
  in_progress: 'bg-sky-100 text-sky-800 dark:bg-sky-900/30 dark:text-sky-300',
  completed: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300',
}

function todayDateKey() {
  const now = new Date()
  const local = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
  return local.toISOString().slice(0, 10)
}

function formatProjectLabel(project: TaskProject) {
  const poNumber = project.poNumber?.trim()
  return poNumber ? `PO ${poNumber} - ${project.name}` : project.name
}

function isTaskUrgent(task: Task) {
  const today = new Date()
  const alarmDate = task.alarmDate ? new Date(task.alarmDate) : null
  const dueDate = task.dueDate ? new Date(task.dueDate) : null

  if (alarmDate && alarmDate <= today) return true
  if (dueDate && dueDate <= new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000)) return true // within 7 days
  return false
}

export function TasksModule() {
  const { locale, t } = useI18n()
  const [statusFilter, setStatusFilter] = useState<string>('all')
  const [projectFilter, setProjectFilter] = useState<string>('all')
  const [dialogOpen, setDialogOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const [form, setForm] = useState<TaskFormData>(emptyForm)

  const queryClient = useQueryClient()

  const { data: tasks = [], isLoading } = useQuery<Task[]>({
    queryKey: ['tasks', statusFilter, projectFilter],
    queryFn: () =>
      fetch(`/api/tasks${statusFilter && statusFilter !== 'all' ? `?status=${statusFilter}` : ''}${projectFilter && projectFilter !== 'all' ? `${statusFilter !== 'all' ? '&' : '?'}projectId=${projectFilter}` : ''}`).then(
        (response) => response.json()
      ),
  })

  const { data: projects = [] } = useQuery<TaskProject[]>({
    queryKey: ['tasks-projects'],
    queryFn: () => fetch('/api/projects').then((response) => response.json()),
  })

  const { data: personnel = [] } = useQuery<PersonOption[]>({
    queryKey: ['personnel'],
    queryFn: () => fetch('/api/personnel').then((response) => response.json()),
  })

  const personnelByKey = useMemo(() => {
    const map = new Map<string, PersonOption>()
    for (const person of personnel) map.set(`${person.type}:${person.id}`, person)
    return map
  }, [personnel])

  function buildTaskPayload(data: TaskFormData) {
    const { assigneeKey, ...rest } = data
    const { assigneeType, assigneeId } = parseAssigneeKey(assigneeKey)
    return { ...rest, assigneeType, assigneeId }
  }

  const createMutation = useMutation({
    mutationFn: (data: TaskFormData) =>
      fetch('/api/tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(buildTaskPayload(data)),
      }).then((response) => response.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] })
      queryClient.invalidateQueries({ queryKey: ['calendar-tasks'] })
      toast.success(t('tasks.toast.created'))
      closeDialog()
    },
    onError: () => toast.error(t('tasks.toast.createError')),
  })

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: TaskFormData }) =>
      fetch(`/api/tasks/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(buildTaskPayload(data)),
      }).then((response) => response.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] })
      queryClient.invalidateQueries({ queryKey: ['calendar-tasks'] })
      toast.success(t('tasks.toast.updated'))
      closeDialog()
    },
    onError: () => toast.error(t('tasks.toast.updateError')),
  })

  const toggleCompleteMutation = useMutation({
    mutationFn: (task: Task) =>
      fetch(`/api/tasks/${task.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: task.status === 'completed' ? 'pending' : 'completed' }),
      }).then((response) => response.json()),
    onSuccess: (_task, originalTask) => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] })
      queryClient.invalidateQueries({ queryKey: ['calendar-tasks'] })
      toast.success(originalTask.status === 'completed' ? t('tasks.toast.reopened') : t('tasks.toast.completed'))
    },
    onError: () => toast.error(t('tasks.toast.updateError')),
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) =>
      fetch(`/api/tasks/${id}`, { method: 'DELETE' }).then((response) => response.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] })
      queryClient.invalidateQueries({ queryKey: ['calendar-tasks'] })
      toast.success(t('tasks.toast.deleted'))
      setDeleteOpen(false)
      setDeletingId(null)
    },
    onError: () => toast.error(t('tasks.toast.deleteError')),
  })

  function openCreate() {
    setEditingId(null)
    setForm(emptyForm)
    setDialogOpen(true)
  }

  function openEdit(task: Task) {
    setEditingId(task.id)
    setForm({
      title: task.title,
      description: task.description,
      dueDate: task.dueDate || '',
      alarmDate: task.alarmDate || '',
      completedAt: task.completedAt || '',
      projectId: task.projectId || '',
      status: task.status,
      assigneeKey: makeAssigneeKey(task.assigneeType, task.assigneeId),
    })
    setDialogOpen(true)
  }

  function closeDialog() {
    setDialogOpen(false)
    setEditingId(null)
    setForm(emptyForm)
  }

  function handleSubmit(event: React.FormEvent) {
    event.preventDefault()
    if (!form.title.trim()) return

    const payload = {
      ...form,
      completedAt: form.status === 'completed' ? form.completedAt || todayDateKey() : '',
    }

    if (editingId) {
      updateMutation.mutate({ id: editingId, data: payload })
    } else {
      createMutation.mutate(payload)
    }
  }

  const isMutating = createMutation.isPending || updateMutation.isPending

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2">
          <Filter className="h-4 w-4 text-muted-foreground" />
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder={t('tasks.filters.placeholder')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('tasks.filters.all')}</SelectItem>
              <SelectItem value="pending">{t('dashboard.status.pending')}</SelectItem>
              <SelectItem value="in_progress">{t('dashboard.status.inProgress')}</SelectItem>
              <SelectItem value="completed">{t('dashboard.status.completed')}</SelectItem>
            </SelectContent>
          </Select>
          <Select value={projectFilter} onValueChange={setProjectFilter}>
            <SelectTrigger className="w-[200px]">
              <SelectValue placeholder={t('tasks.filters.project')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('tasks.filters.allProjects')}</SelectItem>
              {projects.map((project) => (
                <SelectItem key={project.id} value={project.id}>
                  {formatProjectLabel(project)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <Button onClick={openCreate} size="sm">
          <Plus className="mr-2 h-4 w-4" />
          {t('tasks.actions.new')}
        </Button>
      </div>

      {isLoading ? (
        <div className="rounded-lg border p-8 text-center text-sm text-muted-foreground">
          {t('tasks.loading')}
        </div>
      ) : tasks.length === 0 ? (
        <EmptyState
          icon={ListTodo}
          title={t('tasks.emptyTitle')}
          description={statusFilter !== 'all' ? t('tasks.emptyFiltered') : t('tasks.emptyDescription')}
          action={
            statusFilter === 'all' ? (
              <Button variant="outline" size="sm" onClick={openCreate}>
                <Plus className="mr-2 h-4 w-4" />
                {t('tasks.actions.add')}
              </Button>
            ) : undefined
          }
        />
      ) : (
        <div className="overflow-x-auto rounded-lg border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-12">{t('tasks.table.complete')}</TableHead>
                <TableHead>{t('tasks.table.title')}</TableHead>
                <TableHead className="hidden md:table-cell">{t('tasks.table.description')}</TableHead>
                <TableHead className="hidden lg:table-cell">{t('tasks.table.project')}</TableHead>
                <TableHead className="hidden sm:table-cell">{t('tasks.table.dueDate')}</TableHead>
                <TableHead className="hidden lg:table-cell">{t('tasks.table.alarmDate')}</TableHead>
                <TableHead>{t('tasks.table.status')}</TableHead>
                <TableHead className="text-right">{t('common.actions')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {tasks.map((task) => {
                const statusClass = STATUS_CLASSNAME[task.status] || STATUS_CLASSNAME.pending
                const assignee = task.assigneeType && task.assigneeId
                  ? personnelByKey.get(`${task.assigneeType}:${task.assigneeId}`)
                  : undefined
                const AssigneeIcon = assignee?.type === 'contractor' ? Building2 : HardHat

                return (
                  <TableRow key={task.id}>
                    <TableCell>
                      <Checkbox
                        checked={task.status === 'completed'}
                        disabled={toggleCompleteMutation.isPending}
                        aria-label={
                          task.status === 'completed'
                            ? t('tasks.actions.reopen')
                            : t('tasks.actions.complete')
                        }
                        onCheckedChange={() => toggleCompleteMutation.mutate(task)}
                      />
                    </TableCell>
                    <TableCell className="font-medium">
                      <div className="space-y-1">
                        <div className={`flex items-center gap-2 ${task.status === 'completed' ? 'text-muted-foreground line-through' : ''}`}>
                          {isTaskUrgent(task) && <Badge variant="destructive" className="text-xs">Urgente</Badge>}
                          {task.autoGenerated && (
                            <span className="shrink-0 rounded border border-amber-300 bg-amber-50 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-amber-700 dark:border-amber-700 dark:bg-amber-950/40 dark:text-amber-400">
                              Auto
                            </span>
                          )}
                          <span>{task.title}</span>
                        </div>
                        {assignee && (
                          <div className="inline-flex w-fit items-center gap-1 rounded-full border bg-muted/40 px-2 py-0.5 text-xs font-normal text-foreground">
                            <AssigneeIcon className="h-3 w-3 text-muted-foreground" />
                            <span className="truncate">{assignee.name}</span>
                          </div>
                        )}
                        {task.project && (
                          <div className="flex items-center gap-1 text-xs font-normal text-muted-foreground lg:hidden">
                            <FolderKanban className="h-3 w-3" />
                            <span className="truncate">{formatProjectLabel(task.project)}</span>
                          </div>
                        )}
                        {task.alarmDate && (
                          <div className="flex items-center gap-1 text-xs font-normal text-muted-foreground lg:hidden">
                            <Bell className="h-3 w-3" />
                            <span>
                              {formatLocaleDate(locale, task.alarmDate, {
                                day: 'numeric',
                                month: 'short',
                                year: 'numeric',
                              }) || '-'}
                            </span>
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="hidden max-w-[200px] md:table-cell">
                      <span className="block truncate text-sm text-muted-foreground">
                        {task.description || '-'}
                      </span>
                    </TableCell>
                    <TableCell className="hidden max-w-[220px] text-sm lg:table-cell">
                      {task.project ? (
                        <span className="flex items-center gap-1 text-muted-foreground">
                          <FolderKanban className="h-3.5 w-3.5 shrink-0" />
                          <span className="truncate">{formatProjectLabel(task.project)}</span>
                        </span>
                      ) : (
                        '-'
                      )}
                    </TableCell>
                    <TableCell className="hidden text-sm sm:table-cell">
                      {task.dueDate
                        ? formatLocaleDate(locale, task.dueDate, {
                            day: 'numeric',
                            month: 'short',
                            year: 'numeric',
                          }) || '-'
                        : '-'}
                    </TableCell>
                    <TableCell className="hidden text-sm lg:table-cell">
                      {task.alarmDate ? (
                        <span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-0.5 text-xs font-medium text-amber-700 dark:bg-amber-900/30 dark:text-amber-300">
                          <Bell className="h-3 w-3" />
                          {formatLocaleDate(locale, task.alarmDate, {
                            day: 'numeric',
                            month: 'short',
                            year: 'numeric',
                          }) || '-'}
                        </span>
                      ) : (
                        '-'
                      )}
                    </TableCell>
                    <TableCell>
                      <div className="space-y-1">
                        <Badge variant="secondary" className={statusClass}>
                          {task.status === 'completed' ? (
                            <CheckCircle2 className="mr-1 h-3 w-3" />
                          ) : (
                            <Circle className="mr-1 h-3 w-3" />
                          )}
                          {t(getTaskStatusKey(task.status))}
                        </Badge>
                        {task.completedAt && (
                          <div className="text-xs text-muted-foreground">
                            {t('tasks.completedAt.short', {
                              date:
                                formatLocaleDate(locale, task.completedAt, {
                                  day: 'numeric',
                                  month: 'short',
                                  year: 'numeric',
                                }) || '-',
                            })}
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex items-center justify-end gap-1">
                        <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => openEdit(task)}>
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 text-destructive hover:text-destructive"
                          onClick={() => {
                            setDeletingId(task.id)
                            setDeleteOpen(true)
                          }}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                )
              })}
            </TableBody>
          </Table>
        </div>
      )}

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{editingId ? t('tasks.dialog.editTitle') : t('tasks.dialog.createTitle')}</DialogTitle>
          </DialogHeader>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="title">{t('tasks.fields.title')}</Label>
              <Input
                id="title"
                value={form.title}
                onChange={(event) => setForm({ ...form, title: event.target.value })}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="description">{t('tasks.fields.description')}</Label>
              <Textarea
                id="description"
                value={form.description}
                onChange={(event) => setForm({ ...form, description: event.target.value })}
                rows={3}
              />
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="projectId">{t('tasks.fields.project')}</Label>
                <Select
                  value={form.projectId || NO_PROJECT_VALUE}
                  onValueChange={(value) =>
                    setForm({ ...form, projectId: value === NO_PROJECT_VALUE ? '' : value })
                  }
                >
                  <SelectTrigger id="projectId">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={NO_PROJECT_VALUE}>{t('tasks.fields.noProject')}</SelectItem>
                    {projects.map((project) => (
                      <SelectItem key={project.id} value={project.id}>
                        {formatProjectLabel(project)}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="assignee">Asignar a</Label>
                <Select
                  value={form.assigneeKey || NO_ASSIGNEE_VALUE}
                  onValueChange={(value) =>
                    setForm({ ...form, assigneeKey: value === NO_ASSIGNEE_VALUE ? '' : value })
                  }
                >
                  <SelectTrigger id="assignee">
                    <SelectValue placeholder="Sin asignar" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={NO_ASSIGNEE_VALUE}>Sin asignar</SelectItem>
                    {personnel.filter((p) => p.type === 'contractor').length > 0 && (
                      <>
                        <div className="px-2 pt-1.5 pb-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                          Contratistas
                        </div>
                        {personnel
                          .filter((p) => p.type === 'contractor')
                          .map((person) => (
                            <SelectItem key={`contractor:${person.id}`} value={`contractor:${person.id}`}>
                              {person.name}
                            </SelectItem>
                          ))}
                      </>
                    )}
                    {personnel.filter((p) => p.type === 'installer').length > 0 && (
                      <>
                        <div className="px-2 pt-1.5 pb-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                          Instaladores
                        </div>
                        {personnel
                          .filter((p) => p.type === 'installer')
                          .map((person) => (
                            <SelectItem key={`installer:${person.id}`} value={`installer:${person.id}`}>
                              {person.name}
                            </SelectItem>
                          ))}
                      </>
                    )}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="dueDate">{t('tasks.fields.dueDate')}</Label>
                <Input
                  id="dueDate"
                  type="date"
                  value={form.dueDate}
                  onChange={(event) => setForm({ ...form, dueDate: event.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="alarmDate">{t('tasks.fields.alarmDate')}</Label>
                <Input
                  id="alarmDate"
                  type="date"
                  value={form.alarmDate}
                  onChange={(event) => setForm({ ...form, alarmDate: event.target.value })}
                />
              </div>
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="status">{t('tasks.fields.status')}</Label>
                <Select
                  value={form.status}
                  onValueChange={(value) =>
                    setForm({
                      ...form,
                      status: value,
                      completedAt: value === 'completed' ? form.completedAt || todayDateKey() : '',
                    })
                  }
                >
                  <SelectTrigger id="status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="pending">{t('dashboard.status.pending')}</SelectItem>
                    <SelectItem value="in_progress">{t('dashboard.status.inProgress')}</SelectItem>
                    <SelectItem value="completed">{t('dashboard.status.completed')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>{t('tasks.fields.completedAt')}</Label>
                <div className="flex min-h-9 items-center rounded-md border bg-muted/40 px-3 text-sm text-muted-foreground">
                  {form.completedAt
                    ? formatLocaleDate(locale, form.completedAt, {
                        day: 'numeric',
                        month: 'short',
                        year: 'numeric',
                      })
                    : t('calendar.noDate')}
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={closeDialog}>
                {t('common.cancel')}
              </Button>
              <Button type="submit" disabled={isMutating}>
                {isMutating ? t('tasks.actions.saving') : editingId ? t('tasks.actions.update') : t('common.create')}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <ConfirmDeleteDialog
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        onConfirm={() => deletingId && deleteMutation.mutate(deletingId)}
        title={t('tasks.delete.title')}
        description={t('tasks.delete.description')}
      />
    </div>
  )
}
