import type { WarehouseBlueprint } from './types'

export const DEFAULT_WAREHOUSE_BLUEPRINT: WarehouseBlueprint = {
  id: 'default-wh-blueprint',
  canvas: {
    width: 760,
    height: 1240,
  },
  annotations: [
    { label: 'Muro norte', x: 92, y: 32 },
    { label: 'Pasillo central', x: 326, y: 585 },
    { label: 'Zona auxiliar', x: 492, y: 1090 },
  ],
  slots: [
    {
      key: 'RACK_A',
      displayName: 'Rack A',
      aliases: ['RACK A', 'RACKA', 'A'],
      rackType: 'single',
      x: 82,
      y: 90,
      width: 138,
      height: 246,
      tone: 'primary',
    },
    {
      key: 'RACK_B',
      displayName: 'Rack B',
      aliases: ['RACK B', 'RACKB', 'B'],
      rackType: 'single',
      x: 82,
      y: 390,
      width: 138,
      height: 246,
      tone: 'primary',
    },
    {
      key: 'RACK_C',
      displayName: 'Rack C',
      aliases: ['RACK C', 'RACKC', 'C'],
      rackType: 'double',
      x: 288,
      y: 110,
      width: 152,
      height: 228,
      tone: 'primary',
    },
    {
      key: 'RACK_D',
      displayName: 'Rack D',
      aliases: ['RACK D', 'RACKD', 'D'],
      rackType: 'double',
      x: 500,
      y: 110,
      width: 152,
      height: 228,
      tone: 'primary',
    },
    {
      key: 'RACK_F',
      displayName: 'Rack F',
      aliases: ['RACK F', 'RACKF', 'F'],
      rackType: 'double',
      x: 288,
      y: 390,
      width: 152,
      height: 228,
      tone: 'primary',
    },
    {
      key: 'RACK_AUX',
      displayName: 'Rack AUX',
      aliases: ['RACK AUX', 'RACKAUX', 'AUX'],
      rackType: 'double',
      x: 500,
      y: 390,
      width: 168,
      height: 214,
      tone: 'aux',
    },
    {
      key: 'RACK_AXU',
      displayName: 'Rack AXU',
      aliases: ['RACK AXU', 'RACKAXU', 'AXU'],
      rackType: 'double',
      x: 288,
      y: 690,
      width: 168,
      height: 214,
      tone: 'aux',
    },
    {
      key: 'FASTNER',
      displayName: 'Fastner',
      aliases: ['FASTNER', 'FASTENER'],
      rackType: 'single',
      x: 82,
      y: 715,
      width: 190,
      height: 112,
      tone: 'support',
    },
    {
      key: 'TOOLS',
      displayName: 'Armarios',
      aliases: ['ARMARIOS DE HERRAMIENTAS', 'ARMARIOS', 'TOOLS'],
      rackType: 'single',
      x: 82,
      y: 870,
      width: 190,
      height: 112,
      tone: 'support',
    },
  ],
}
